//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HelloCSharp.Api.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HelloCSharp.Api.Resources.strings", typeof(strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Child.
        /// </summary>
        internal static string RelationshipType_ChildOf_DisplayName {
            get {
                return ResourceManager.GetString("RelationshipType_ChildOf_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is the child of.
        /// </summary>
        internal static string RelationshipType_ChildOf_Message {
            get {
                return ResourceManager.GetString("RelationshipType_ChildOf_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enemies.
        /// </summary>
        internal static string RelationshipType_Hates_DisplayName {
            get {
                return ResourceManager.GetString("RelationshipType_Hates_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hates.
        /// </summary>
        internal static string RelationshipType_Hates_Message {
            get {
                return ResourceManager.GetString("RelationshipType_Hates_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parent.
        /// </summary>
        internal static string RelationshipType_ParentOf_DisplayName {
            get {
                return ResourceManager.GetString("RelationshipType_ParentOf_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is the parent of.
        /// </summary>
        internal static string RelationshipType_ParentOf_Message {
            get {
                return ResourceManager.GetString("RelationshipType_ParentOf_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Partners.
        /// </summary>
        internal static string RelationshipType_Partners_DisplayName {
            get {
                return ResourceManager.GetString("RelationshipType_Partners_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is the partner of.
        /// </summary>
        internal static string RelationshipType_Partners_Message {
            get {
                return ResourceManager.GetString("RelationshipType_Partners_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Siblings.
        /// </summary>
        internal static string RelationshipType_Siblings_DisplayName {
            get {
                return ResourceManager.GetString("RelationshipType_Siblings_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is the sibling of.
        /// </summary>
        internal static string RelationshipType_Siblings_Message {
            get {
                return ResourceManager.GetString("RelationshipType_Siblings_Message", resourceCulture);
            }
        }
    }
}
